### ISSUE TITLE
iOS client (iPad, iPhone)

### ISSUE THREAD

**Issue by a-b** [keithw/mosh#198]
Hello thanks for awesome product,

It would be insanely great to have iOS client so we can connect from iPad.

**Comment by jardimsonoro** [comment]
any news on mosh and ios?

**Comment by a-b** [comment]
:+1:

**Comment by keithw** [comment]
I don't think there's much for us to do here. If the iOS community wants Mosh, somebody will have to pair it with a UI and release it on the App Store.

(It doesn't need a full-fledged terminal emulator, since mosh-client already has one, but it does need some way of displaying characters on the screen and some way of initiating the connection via SSH.)

**Comment by rileytg** [comment]
I'm down to start this and maintain the app if someone with more iOS chops (I'm experienced in other stacks and have a couple years of light iOS dev experience) is around for advice...

**Comment by juhagman** [comment]
@keithw I am interested in helping out with an iOS version. I quickly glanced at the code and am unsure what the interface between the app that draws the view and getting user input would be. 

Where does one get the text to be drawn (and callback that something has changed), how does one give user input back to mosh?

**Comment by cgull** [comment]
Mosh is a console app, it expects to be run on an xterm-like terminal, which provides the actual UI.

There's two plausible ways to make Mosh work on iOS: use mosh-client more or less as is and provide a terminal emulator in your iOS app, or hook into or replace Mosh's core redraw code in Terminal::Display::new_frame().  That code does a lot of work to reduce the size of output to the terminal, since it's used on the server side too to generate the diffs sent over the network.  But for local display you could probably simplify the code a lot without losing much performance.  There's a lot of other stuff you'd need to rework, too, but that's the first thing to look at.

https://github.com/rpwoodbu/mosh-chrome is an example of the first approach, and https://github.com/micolous/mosh-win is an incomplete Win32 port that illustrates the second approach.

**Comment by juhagman** [comment]
Thank you very much for the pointers, @cgull. The first approach sounds like way too much work, the second more approachable. I will look into this during the weekend.

**Comment by hsleewis** [comment]
Any progress on this? would be very awesome :-)

**Comment by spitfire** [comment]
As far as I remember Panic, team behind [Prompt](https://geo.itunes.apple.com/app/prompt-2/id917437289?at=1000lcL&ct=github_prompt-2&mt=8) was considering adding support for mosh protocol to it.

**Comment by rekendahl** [comment]
I think Panic would like to add it but to do that they believe that Mosh needs to be dual licensed under something other then GPL. Panic seem to say GPL is not compatible with the app store. See https://library.panic.com/prompt/prompt-mosh/

I’d love to see Mosh under a different license, like Apache as well. I believe it would spread wider with a more product permissive license. 

/Robert

**Comment by spitfire** [comment]
It's not only what they say - this is a fact. They will probably just do their own implementation of the protocol, like iSSH did. I can't blame them though. Can any of the Mosh authors contact them in that regard?

**Comment by keithw** [comment]
Mosh's license is perfectly compatible with the App Store and has been since 2012. Panic has been in contact with us several times. They have never raised the issue that they believe Mosh's license is incompatible with the app store. They have raised the issue that they do not want to comply with the GPL and open-source the rest of their app. That's their decision.

Mosh has successfully been ported to or distributed on 20+ different platforms -- even if we could change the license at this point, why does this platform deserve special treatment? If there is demand from iOS users for Mosh, anybody is welcome to port it. (You will have to write code that draws the characters in mosh-client's representation of the terminal visually on the screen.)

**Comment by xinan** [comment]
+1!
I wish to see this on Prompt / Coda for iOS soon!

**Comment by uaalto** [comment]
I've read in many places that GPL is compatible per-se with the Apple Store, so the fact that it has GPL is just enough for Apple to reject/ban the app, even if the owners of the project don't pursue it. What's the real situation then?

**Comment by keithw** [comment]
Story is not complicated. Mosh's license has been compatible with the App Store since 2012. Nobody has ported Mosh to iOS. If there is demand from that community, we welcome the port and are happy to assist.

**Comment by logancollins** [comment]
I believe the reason we haven't fully considered implementing Mosh in Prompt and Coda for iOS is not the license of Mosh itself, it's the fact that in order to fully comply with the GPL we'd need to open source our app, or build an interface between the app and the Mosh client library that we would open source. The former isn't really an option for us. The latter presents its own issues on iOS, because it puts some restrictions on dynamic library linking.

If anyone wants to chime in on this specifically in relation to Prompt and Coda, please do! Mosh itself, however, is not the primary reasoning behind why we haven't yet.

**Comment by fitzmorrispr** [comment]
@logancollins
The only reason I haven't purchased Prompt 2 yet is the lack of mosh support. I may buy it eventually anyway, but mosh support would turn that 'may' into a 'will', and the 'eventually' into a 'now'

**Comment by mojoTX** [comment]
I just discovered mosh this evening. I feel like I've been living under a rock. Although I've used SSH since the 1.x days before switching to OpenSSH, I hadn't heard of mosh until I stumbled across it tonight. I'm disappointed to see that iOS support is missing, especially since it seems like a perfect fit. I understand Panic's dilemma of having to choose between open-sourcing their VERY nice Prompt 2.5 product, or coming up with some sort of "arms length" kludge to satisfy the GPL restrictions. We recently had to deal with the "arms length" GPL issue where I work, and it's ugly and kludgey and inefficient. The only thing I dislike so far about mosh is the insistence on GPL. OpenSSH is still the king of secure communications, not because it's better, but because it's licensed under the more permissive and sensible BSD-style license. I suspect mosh adoption is going to be slow as long as it continues to be burdened by GPLv3.

@logancollins, I'm curious if the interface with mosh is really a show-stopper because of technical difficulty with the "arms length" interface, or if the Panic team just don't consider it commercially viable. I am a professional developer myself, and I certainly don't expect you to open source your product. I also suspect that if you DID do an arms-length integration, the performance and quality of your product might suffer. It's pointless and inefficient to add an extra integration layer, especially when one of the goals of the product is to have efficient performance. 

However, I would cheerfully pay extra for an in-app purchase in Prompt 2.5 to add mosh support, especially since mosh appears to be perfect for use from devices like an iPad on sketchy Wi-Fi connections. I suspect with a little promotion, you'd have other customers jumping on it, especially if you explained the technical challenges behind the integration.

I guess the bottom line is that I'd like to know what *I* can do as a Panic customer to help make mosh support in Prompt 2.5 a reality. I am not interested in reinventing the wheel and building an open-source iOS terminal emulator myself; I'd rather just see you add this as a feature, and I'd be willing to pay extra for the functionality.

Also, @keithw, I'm obviously new and don't know the details behind the GPLv3 rationale, but I think I have a good point that most of the really popular encryption products use a BSD-style license, such as OpenSSH and OpenSSL. Continuing to stick with GPLv3 will mean that any mosh clients will by nature need to also be GPL'd, or else do the kludgey arms-length hacks. 

Just my $2e-02.

**Comment by davidjao** [comment]
@mojoTX There are other options. One can implement mosh independently. A separate OCB license is needed in that case. iSSH and JuiceSSH go this route.

**Comment by carloscabanero** [comment]
Hi! I already wrote to the dev list to introduce the project, but I thought it was time to introduce it here too, given how soon we hope to be out. We are a small team that has been working for the last few months on a Mosh based project that I am excited to introduce to you all.
 
Blink is a new mobile shell for iOS. We built the terminal that we ourselves would want to have and use all day long, fully configurable and with a great UI, can't say much more than that right now ;) 
 
We are currently working to have our first release version for testing in the next weeks. This version will only be available to a reduced group of testers, with a next one soon after that for a broader audience. I can advance that, thanks to Mosh, it is at least 5 times faster than any other terminal we have tried!
 
And yep, we will commit to the GPL.
 
I will provide you with more information in the next few days. but in case you would like to test it, or have any feedback, please drop me a private message.
 
Thanks!

**Comment by spitfire** [comment]
@carloscabanero I can't really see a way to DM you here, but I'd be very interested to try this out. Can you leave any contact info (twitter, e-mail,whatever) so I can contact you somehow?

**Comment by rekendahl** [comment]
Not sure how to drop you a private message on GitHub… But I would love to test your shell out. I’m an avid ssh(/mosh)/tmux/vim user and I’ve been trying to find a great solution for the iPad Pro. I’ve tried Prompt but it doesn’t have the colors I want so I’m currently using Jump to remote display my mac’s iterm2 window.

I’d love to be part of beta testing if possible!

/Robert

**Comment by carloscabanero** [comment]
Yup, sorry about that, I'm @carloscabanero on Twitter too.

**Comment by cirqueit** [comment]
@carloscabanero I'm also very interested in a mosh shell

currently using Prompt2 on my iPad Pro  (@logancollins I'd also pay for an in-app upgrade)

**Comment by mojoTX** [comment]
+1...I'd also be interested in participating as a beta tester, @carloscabanero.

Also, @davidjao, thanks for pointing out the independent implementation option. However, I cannot find any sort of detailed documentation for the State Synchronization Protocol (SSP). There's a brief overview in some of the promotional publications, but I haven't been able to find anything written in the same level of technical detail you find in a RFC. 

If a company DID do a "clean room" re-implementation of mosh, I think it would be best to work from standards documents, and NOT even look at the existing GPL implementation. SSH is described by multiple RFCs, and you do not need to download the OpenSSH code if you want to create your own closed-source SSH implementation. 

It's possible that the SSP documentation is out there, but I just haven't found it yet. The mosh research paper only gave an overview, and wasn't something you could use to create an independent implementation.

**Comment by arronmabrey** [comment]
@carloscabanero add me to the list :-)

**Comment by cgull** [comment]
@mojotx-- yes, SSP is an informal protocol and doesn't have any good specification written down.  The best place to start is probably the protobuf definitions, actually.  The protocol itself is fairly straightforward, once you understand that the differences between states are transported largely as character streams with ANSI escape sequences representing screen updates.

It might be good for us to dual-license the protobuf definitions with a permissive license, since it's pretty much impossible to reimplement them in a way that doesn't substantially copy the originals.

While I'm at it, I just noticed that the OpenSSL Software Foundation has a very permissive license from Phillip Rogaway; it looks like it's fine for commercial, closed-source apps.

**Comment by carloscabanero** [comment]
Hi! We are opening our alpha to more people, and would love to prioritize anyone from GH and the mailing list. So if any of you is still interested in Mosh for iOS, please go to https://github.com/blinksh/blink for more instructions, or just follow @BlinkShell and tweet us about your usage scenarios. Thanks for your help!

**Comment by rekendahl** [comment]
I've been lucky to be an early alpha tester. And the app has huge potential but still rough edges. It has best keyboard support of any iOS terminal and it's really fast. Also handles my remote TMUX and vim keyboard shortcut excellent. Better then any other app. There are some graphical and color issues, crashes etc to work out but this shows real potential to be a first page app for me!

Carlos and team is on to something!

**Comment by binaryben** [comment]
Hey @carloscabanero, I was wondering a few things if that's okay. What are you looking for in potential alpha testers for Blink out of interest - is there a "perfect" use case you are hoping will be tested? Also, what sort of price point are you hoping to launch Blink to the App Store at, and are there any approximate timeframes yet?

Honestly, I would pay a bit for it at this point but interested to know if there were any current goals. Am very excited to be able to go completely laptopless without worrying about not having a traditional terminal on my device. Please keep up the good work :)

@rekendahl Your comments are really exciting. I've been trying to use Vim with WebSSH on my iPad Pro. It's alright, but could be better and Mosh support would go a long way to helping that! I had been tossing up whether Prompt would be any better (had actually asked if it was possible for myself to try and code Mosh support for Prompt and then have it integrated with their app). 

Now I am left waiting - I hope it is worthwhile. I like your terminal setup btw (from screenshots in the issues repo for Blink). I think there is a lot to be said for using a terminal that is functional AND looks good. Hopefully colour and font support will be ready soon if they aren't already.

**Comment by carloscabanero** [comment]
So at the start it was about testing our changes to Mosh and our terminal implementation, but that has already been done and it is stable. Next versions will be just about testing the experience, configuration, etc...

I got extremely delayed due to changes in the ssh and ssl code. Great news is that ssh is now working too thanks to that. I'm currently working on opening the code to everyone under the GPL, hopefully done asap. If we have everyone's blessing then we will go straight to the AppStore.

We can discuss about font and color in Blink GH, but Blink supports HTerm, same terminal Google is using in Chromium, so you have full font and color configuration over CSS.

**Comment by binaryben** [comment]
All good to hear, will keep discussing in the blink repo as requested :)

**Comment by andrius** [comment]
I (and I believe many developers) would pay for IOS ssh client with following capabilities:

- mosh support;
- port forwarding (both local and dynamic) support;
- good support for logitech and apple smart keyboard (currently pgup, pgdown, home and end won't work in many ssh clients)

On my iPad Pro I am currently using a zoo: Prompt and Coda, Serverauditor (because of tunnels), and iSSH (yes, I still have it and I boutght mosh in past, it works).

@carloscabanero: definitely I would be happy to participate in testing!

**Comment by NathanielCapital** [comment]
@andrius Yes, I am doing exactly the same thing. I also use Xcute, which good for quick peek for information. Unfortunately I no longer have the iSSH copy I bought :(,  is there a way I can have copy somewhere and install it?( Bought it, but no longer available for download on ITunes)

**Comment by carloscabanero** [comment]
Hope everyone is doing well, I just wanted to give a heads up that [Blink](http://blink.sh) was released a month ago and the next version is coming soon (already available for testers). I would be very grateful if you could update mosh.org with a link to our repository & to blink.sh.

We have simplified compiling a lot so if you want to give it a try, head to the [Blink Shell repo](https://github.com/blinksh/blink) and make sure to let us know what you think. We already have a few contributors and any feedback / ideas / PRs you might have are very welcome :) 

Our Raw branch is still open for testing, for those of you who do not even want to touch Xcode even with a fork (I’m becoming one of those too). Tweet us [@BlinkShell](https://twitter.com/blinkshell) and we will send you a DM with more information.

We ran a very cool video comparing Mosh and SSH. I had never seen Mosh echo in action in such an obvious way, and it is awesome! If you would like to use it on mosh.org, I can very easily remove the Blink part at the end ;)
https://youtu.be/f_2SI-YxsaY

Thanks!

**Comment by keithw** [comment]
Great! Can you please send a pull request to https://github.com/mobile-shell/moshweb for what you would like on the website?

**Comment by carloscabanero** [comment]
Sorry Keith, didn't see that repo. Just did the PR. Thanks!
