### ISSUE TITLE
feature request - replace/restart mosh-server on requested port

### ISSUE THREAD

**Issue by fungs** [keithw/mosh#585]
Hi,

it often happens to me that a running mosh session isn't responding any more or the original device is not going to reconnect. As I'm using a single UDP port, I have to kill the mosh server before I can run a new one on the server. It would be really useful if the mosh wrapper could detect a running server on a port by the same user and then kill this server and start a new one or send the server a signal which will cause the server to create and report a new key somehow.

**Comment by keithw** [comment]
What many people do in this situation is to start the session with:
`mosh hostname -- screen` (or tmux equivalent)

and then if they need to kill the only one and start a new one, run:
`mosh hostname -- screen -dr`

This will kill the old session (freeing the UDP port) and then start a new session attached to the same virtual screen.

Your best bet is just to get rid of the block on UDP ports (instead of trying to always tell the program which one to use), but this is workable.

**Comment by cgull** [comment]
That suggested workaround doesn't help the specific case outlined here because it kills the old mosh server after the new one has been started, which doesn't free the single fixed UDP port in time.  What you want to do is check for and stop the existing mosh-server before starting a new one.  Like many similar issues, this one is solvable with a little scripting on client and/or server side.

**Comment by fungs** [comment]
@keithw: I haven't checked your solution but to me it seems to not work for me, as commented by @cgull. Also, I can't find the definition of -- in the manpage of my program version (mosh 1.2.4).

Maybe I was a little imprecise. The feature request was for a replace option in the mosh wrapper program which would do exactly what @cgull is suggesting; with a single connect. Of course I can do it manually.

Having more ports wouldn't solve the problem when I'm connecting from the same device after the server has become unresponsive. It would just leave more mosh-server processes hanging around.

**Comment by keithw** [comment]
@fungs: The screen approach will kill the old mosh-server (since you're detaching the old screen and causing the old mosh-server to exit)  -- it won't leave it hanging around.

Whether it does so in time to free up the port is another question, and cgull may be right on that.

**Comment by cgull** [comment]
Sorry, I should have provided a more useful answer last time-- I was a 
little rushed.

The mosh script is generous in what sorts of arguments it'll execute for 
--client and --server.  I said "scripting", but a very simple solution 
to this could be:

mosh --server='pkill mosh-server; mosh-server' remote-host -- screen -dr

That kills off any mosh-server with your uid (but don't do this as root, 
folks) and then starts a new mosh-server, which then takes port 60001 if 
available.  You could elaborate the --server argument shown here, or 
deploy a little script server-side, to be smarter about deciding which 
mosh-server to kill.  You may not need anything much more elaborate than 
this anyway; the problem you're having can only be solved when there's 
one user using one mosh-server on the machine, for which this simple 
solution is fine.

   --jh
