### ISSUE TITLE
make script fails: userinput.pb.h:17:2: error: #error This file was generated by an older version of protoc

### ISSUE THREAD

**Issue by adab3ta** [keithw/mosh#587]
Trying to compile Mosh without root on my system, and running into this problem with Protocol Buffers.

I found this problem on SO: http://stackoverflow.com/questions/17525145/protocol-buffers-version-error-when-trying-to-make-mosh-source-code that is similar with no solution.  

My error output is here: https://gist.github.com/adab3ta/5bc039e7b432a1074d77

I had been referring to instructions from http://www.saicharan.in/blog/2012/07/27/installing-mosh-from-source/ and using the latest source for PB and Mosh.

**Comment by andersk** [comment]
Given those instructions and the error you received, you are probably mixing the system version of `protoc` (`/usr/bin/protoc`) with a local version of the protobuf headers in your home directory. You can’t do that. I would recommend deleting the local version and skipping the step where you build protobuf in your home directory, because it is already installed system-wide.
