### ISSUE TITLE
request: mosh-server to accept externally provided keys

### ISSUE THREAD

**Issue by vanrein** [keithw/mosh#588]
Mosh assumes an external setup protocol, such as SSH, and wants to be open to many of those.  But I found that its one-sided session key generation can make some alternative schemes impossible or less useful:

* With TLS, it could make sense to use [RFC 5705](https://tools.ietf.org/html/rfc5705) to continue with a key generated from the TLS session, thus establishing a cryptographic binding between session key and authenticated context.

* With Kerberos, it could be useful to export a session secret for use in MOSH.  Normally, this is KDC-generated, but [extensions](http://tools.ietf.org/html/draft-vanrein-krb5-kdh) may incorporate forward secrecy without sacrificing the cryptographic link to Kerberos authentication.

Note that forward secrecy has an advantage over what mosh now does; it incorporates cryptographic material from both ends and is not dependent on a pre-existing encryption channel to protect against tapping.

So the requested feature is an option that instructs mosh-server to pickup an externally provided secret, like mosh-client does it.  Revealing it in its output would typically not be needed, and may even be a bad idea.

**Comment by andersk** [comment]
SSH does have forward secrecy. Mosh itself has no long-term keys or any other kind of cross-session state, so forward secrecy is not otherwise an issue.

If you want to bind a Mosh session to a custom externally provided secret, all you have to do is let Mosh generate its own random key as usual, encrypt that random key using some authenticated cipher with your externally provided secret, and pass it along to the client that way.
