### ISSUE TITLE
Fix bash_completion (location and contents)

### ISSUE THREAD

**Issue by keithw** [keithw/mosh#628]
Our bash_completion file allegedly has the wrong contents:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782169

And gets installed in the wrong location:
https://lintian.debian.org/maintainer/keithw@mit.edu.html#mosh

**Comment by keithw** [comment]
Partial dup of #518

**Comment by andersk** [comment]
This is going to break bash completion on older systems like Ubuntu 12.04 precise. The new location `/usr/share/bash-completion/completions` is only supported by bash-completion ≥ 2.

We need to do something like
```
AS_IF([test "$install_completion" != no],
  [PKG_CHECK_MODULES([BASH_COMPLETION], [bash-completion >= 2.0],
     [completionsdir="`pkg-config --variable=completionsdir bash-completion`"],
     [completionsdir="${sysconfdir}/bash-completion.d"])
   AC_SUBST([completionsdir])])
```

then install to `${completionsdir}`, and have the Debian package build-depend on bash-completion.

**Comment by mrueg** [comment]
@andersk Please introduce something like --enable-completions-compat for old systems.

**Comment by cgull** [comment]
Wups, I got mixed up on finishing this fix.  
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776954 suggests using dh_bash_completion at install time.  Now I just need to find out how far back **that** is available.  I assume we'd install directly to the old location otherwise.

There's also the question of backward compatibility for the features the new completion support uses.

**Comment by andersk** [comment]
`/usr/share/bash-completion/completions` is a new feature of bash-completion 2. It’s not just a different directory name; it has different semantics as well, in that bash-completion loads files from there dynamically on demand, rather than all at once on shell startup.

To be sure that something funny isn’t going on, I checked that bash-completion 1.3 on RHEL 6 (EPEL) does not support `/usr/share/bash-completion/completions`.

`dh_bash-completion` exists on all Debian and Ubuntu releases that are still supported.

**Comment by cgull** [comment]
Sorry, I wasn't clear.  For "backward compatibility", I really meant "the helper functions used by the new completion snippet".

I'll work on it tonight, but if anybody experienced in these issues wants to contribute, please do-- I have little knowledge about bash completion.

**Comment by cgull** [comment]
I've reverted my original commit-- it was more broken than I originally thought.  I think I have a better fix, but it needs more testing.  I'll put it up as a PR first, probably tomorrow.

**Comment by cgull** [comment]
@andersk, @mrueg, @achernya, please review <https://github.com/cgull/mosh/commit/dee1a2eecc9a2355d1818205292e403143fc0554>.  It's a much more complete resolution of this issue.

It's tested on Ubuntu 15.04, 14.10, 12.04, and Raspbian (but the conffile issue was only tested on 14.10).

`dh_bash-completion` turns out to be useless, it still has `/etc/bash_completion.d` hard-coded.  The helper functions are available way back, so they are OK.

@mrueg, I think the answer to your request is "build dependencies" (which this diff has).  If that doesn't work for you, there's always `--disable-bash-completion`.

I'm thoroughly amazed at how much time this has eaten.
