### ISSUE TITLE
Installation is incompatible with OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by reanimus** [keithw/mosh#648]
I imagine the installation is incompatible with System Integrity Protection. When I updated my system to the 10.11 public beta, mosh was gone, and attempts to reinstall it failed. The log is available [here](https://gist.github.com/reanimus/b74e6bd6a268b123580d), but the pertinent sections are probably these:

```
Jul 12 16:12:39 Singularity Installer[1358]: Package generated system content warning: Error Domain=IFInstallErrorDomain Code=-5000 "This package is incompatible with this version of OS X and may fail to install." UserInfo=0x7fff4c7312d0 {NSLocalizedRecoveryOptions=(
	    "Cancel Installation",
	    "Install Anyway"
	), NSLocalizedRecoverySuggestion=Installing this package may damage your system, and the installation may fail. To stop the program and the installation, click “Cancel Installation”., IFSystemPathsKey=(
	    "usr/bin/mosh-server",
	    "usr/bin/mosh-client",
	    "usr/bin/mosh",
	    "usr/etc"
	), NSLocalizedDescription=This package is incompatible with this version of OS X and may fail to install.}
```

```
Jul 12 16:12:41 Singularity shove[1399]: [source=file] failed _RelinkFile(/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/151ADB83-E75D-4D19-AA2B-9B96409FDE19.activeSandbox/Root/usr/bin/mosh, /usr/bin/mosh): No such file or directory
Jul 12 16:12:41 Singularity shove[1399]: srcPath = /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/PKInstallSandboxManager/151ADB83-E75D-4D19-AA2B-9B96409FDE19.activeSandbox/Root/usr/bin/mosh NSFileOwnerAccountID=0 NSFileHFSTypeCode=0 NSFileSystemFileNumber=76814148 NSFileExtensionHidden=0 NSFileSystemNumber=16777225 NSFileSize=8836 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2013-05-16 22:07:41 +0000 NSFilePosixPermissions=509 NSFileHFSCreatorCode=0 NSFileType=NSFileTypeRegular NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=1 NSFileModificationDate=2013-05-16 22:07:41 +0000
Jul 12 16:12:41 Singularity shove[1399]: dstPath = /usr/bin/mosh does not exist
Jul 12 16:12:41 Singularity shove[1399]: dstParentPath = /usr/bin NSFileOwnerAccountID=0 NSFileSystemFileNumber=76113241 NSFileExtensionHidden=0 NSFileSystemNumber=16777225 NSFileSize=36040 NSFileGroupOwnerAccountID=0 NSFileOwnerAccountName=root NSFileCreationDate=2015-07-03 17:20:57 +0000 NSFilePosixPermissions=493 NSFileType=NSFileTypeDirectory NSFileGroupOwnerAccountName=wheel NSFileReferenceCount=1060 NSFileModificationDate=2015-07-09 22:35:15 +0000
```

Mosh is attempting to install to directories protected by System Integrity Protection; as far as I can tell these can only be installed to by either disabling the security feature or having your code signed by Apple. It's still possible to install to /usr/local with System Integrity Protection enabled though. Perhaps that might work (unless you guys are willing to somehow get your code signed by Apple, in which case go for it, haha)

**Comment by keithw** [comment]
Thanks for the report. We are just about to do a 1.2.5 release with a new way of building the OS X binary installer. Could you please test http://www.glup.org/cgull/mosh-1.2.5.pkg and let us know if this fixes the problem (or gives different results at all)?

Thanks,
Keith

**Comment by reanimus** [comment]
Yep, that fixed it! Thanks! :D

**Comment by tr3buchet** [comment]
I can't get it to install at all for me. During the upgrade to osx 10.11.1 it moved the previous installation `1.2.4-3` to a quarantine. Installing `1.2.5` seemed to work but it installed something to `/usr/local/Library/Aliases/mosh` that was not executable. I removed that and tried installing again. The installer says it finished successfully but does nothing that i can tell.

All the mosh files I can find:
``
lappy386:Downloads trey$ find / -name "*mosh*" 2>/dev/null
/Library/SystemMigration/History/Migration-78244139-614E-46D6-9988-2B7276DDED49/QuarantineRoot/usr/bin/mosh
/Library/SystemMigration/History/Migration-78244139-614E-46D6-9988-2B7276DDED49/QuarantineRoot/usr/bin/mosh-client
/Library/SystemMigration/History/Migration-78244139-614E-46D6-9988-2B7276DDED49/QuarantineRoot/usr/bin/mosh-server
/Library/SystemMigration/History/Migration-78244139-614E-46D6-9988-2B7276DDED49/QuarantineRoot/usr/share/man/man1/mosh-client.1
/Library/SystemMigration/History/Migration-78244139-614E-46D6-9988-2B7276DDED49/QuarantineRoot/usr/share/man/man1/mosh-server.1
/Library/SystemMigration/History/Migration-78244139-614E-46D6-9988-2B7276DDED49/QuarantineRoot/usr/share/man/man1/mosh.1
/private/var/db/receipts/edu.mit.mosh.mosh.pkg.bom
/private/var/db/receipts/edu.mit.mosh.mosh.pkg.plist
/Users/trey/Downloads/mosh-1.2.4-3.pkg
/Users/trey/Downloads/mosh-1.2.5.pkg
/usr/local/share/man/man1/mosh-client.1
/usr/local/share/man/man1/mosh-server.1
/usr/local/share/man/man1/mosh.1
/usr/share/zsh/5.0.8/functions/_mosh
``

If I attempt to run the old mosh by executing `/Library/SystemMigration/History/Migration-78244139-614E-46D6-9988-2B7276DDED49/QuarantineRoot/usr/bin/mosh` it seems to work. Surely this isn't expected behavior?

**Comment by cgull** [comment]
Just to be clear, you are installing `mosh-1.2.5.pkg` (md5 `8a6164d8b1e2bbbcc3743f87cea1564e`) available from `mosh.mit.edu` on a machine that had `mosh-1.2.4-3.pkg` installed, then upgraded to OS X 10.11?  Did you have any other mosh installs on the system (Homebrew, Macports, `make install`?)  Did you do the install by using `installer` from the command line or by opening the package with the GUI?

I just tried installing `mosh-1.2.5.pkg` onto my 10.11.1 install here, it works fine.

The quarantine is expected, of course.  On my system, `/usr/local/Library/Aliases/mosh` is a symlink to the Homebrew formula, and is I think unrelated to the package.

The only things I can come up with are that 1) the quarantine of the old install somehow confuses the installer (I'm not sure I checked for correct behavior after my 10.10 -> 10.11 upgrades, but I think I did), or 2) some system protection or antivirus code is blocking the installer's actions.

Can you check `/var/log/install.log` for the time period of the install?
